### ISSUE TITLE
About Page 

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#1]
Take an look at the Figma FIle for reference :-https://www.figma.com/design/9EePKTLQQBEbIW1FtQKXJJ/Nexus-Website

And start working on About page 

Before start working on this issue make sure to go through the README File thoroughly

**Comment by Anushka-Bhowmick** [comment]
I am willing to work on this. Please assign me this issue.

**Comment by komal-agarwal5** [comment]
@Anushka-Bhowmick assigned it to you.Good luck!

**Comment by Anushka-Bhowmick** [comment]
#11
