### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#2]
Take an look at the Figma FIle for reference :-https://www.figma.com/design/9EePKTLQQBEbIW1FtQKXJJ/Nexus-Website

And start working on Event page 

Before start working on this issue make sure to go through the README File thoroughly

**Comment by prajjwal2-3** [comment]
I am working on this issue❤️

**Comment by komal-agarwal5** [comment]
@prajjwal2-3 Assigned it to you.Good luck!

**Comment by Shinjan-saha** [comment]
UI Done
