### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by komal-agarwal5** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#23]
From the Figma file mentioned in the readme, check out the stats page with the stats and testimonials section.
Work on this page.

**Comment by Shinjan-saha** [comment]
It will be in home page as an section don't create an Sepearte page for it

**Comment by SumanJain2005** [comment]
Please assign this me !!!

**Comment by komal-agarwal5** [comment]
@SumanJain2005 Assigned

**Comment by Shinjan-saha** [comment]
#24 PR Merged
