### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#3]
Take an look at the Figma FIle for reference :-https://www.figma.com/design/9EePKTLQQBEbIW1FtQKXJJ/Nexus-Website

And start working on Team  page 
make sure to create an good looking cards for the Team members 
add their Linkdln & github profile 
cuurently use this linkdln post to get details about the core member & start working:-https://www.linkedin.com/feed/update/urn:li:activity:7232234171404853248/

Before start working on this issue make sure to go through the README File thoroughly

**Comment by Shubham-senger** [comment]
I would like to work on this

**Comment by Shinjan-saha** [comment]
@Shubham-senger issue #6 and #7 id already on work for now please look into other issues

**Comment by SRINJAYDASGUPTA-Git** [comment]
@Shinjan-saha May I work on this?

**Comment by SRINJAYDASGUPTA-Git** [comment]
@Shinjan-saha May i work on this issue?

**Comment by Shinjan-saha** [comment]
@SRINJAYDASGUPTA-Git What Changes do you want to do?

**Comment by Shinjan-saha** [comment]
Closing it inactive for long time
