### ISSUE TITLE
Revamp Contact form

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#31]
Make the Contact form look more stylish 
![image](https://github.com/user-attachments/assets/7d749223-cf22-4237-ab26-18527319e9c5)
take inspirtation from but keep the data fields same & the color theme similar to website already there

**Comment by Sp-Sayan** [comment]
assign me this issue @Shinjan-saha

**Comment by Shinjan-saha** [comment]
@Sp-Sayan  assigned you the issue best of luck

**Comment by TechnicallyKiller** [comment]
assign this to me now its been 1 day

**Comment by TechnicallyKiller** [comment]
done with both the issues check the pull request please!! , assign me this issue too hehe

**Comment by Shinjan-saha** [comment]
@TechnicallyKiller you weren't suppose to do any work on any  issue, you were supposed to be assigned it first then only you were supposed to work in it

**Comment by Shinjan-saha** [comment]
#34 PR Merged Closing the issue
