### ISSUE TITLE
Bg Line removing from Contact image 

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#35]
![IMG-20241026-WA0024](https://github.com/user-attachments/assets/ef296e8b-dbaa-4fad-8cd1-1b191119c7b4)
Remove this faint line from right side & Down the image

**Comment by Sp-Sayan** [comment]
fixing it assign me @Shinjan-saha

**Comment by Shinjan-saha** [comment]
#36 PR Done
