### ISSUE TITLE
github and linkedin link addition 

### ISSUE THREAD

**Issue by SumanJain2005** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#37]

**Comment by SumanJain2005** [comment]
assign please

**Comment by Shinjan-saha** [comment]
@SumanJain2005 assigned you the issue best of luck

**Comment by ParthibBiswas10** [comment]
Kindly assign it, please.

**Comment by Shinjan-saha** [comment]
@ParthibBiswas10 this issue has already been assigned plese look into other issues

**Comment by Shinjan-saha** [comment]
Just a Remainder that Tommorow is the last date of Hacktoberfest after that your PR will be no longer consider for Hacktoberfest @SumanJain2005

**Comment by Shinjan-saha** [comment]
#39 PR Merged & Done
