### ISSUE TITLE
Designing cards in Member Page

### ISSUE THREAD

**Issue by Debaditya-Som** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#6]
designing cards and adding linkedin and github profile and images

**Comment by Snehalgupta-07** [comment]
Hi! i can do this task pls assign it to me :)

**Comment by Shinjan-saha** [comment]
1. @Snehalgupta-07 assigned you the issue best of luck

**Comment by Shinjan-saha** [comment]
@Snehalgupta-07 please create the card with dummy data now 
#7 will handle the fill of the member data in the cards which you are designing
