### ISSUE TITLE
Addition of members name

### ISSUE THREAD

**Issue by Debaditya-Som** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#7]
Addition of members list in the members page

**Comment by onlybond** [comment]
Hey there,

I went through the website, repo and the figma file. Is the figma file in the early stages and you are making the changes accordingly in the website. as i can see there is no design for the members page. lemme know if you need any help regarding that.

**Comment by onlybond** [comment]
The names are hardcoded. Should i proceed taking up this issue and work on this?

**Comment by Shinjan-saha** [comment]
@onlybond start the work once from issue #6 is done after the design of the member card is done please then fill the detail of the Members with their github & linkdln details

**Comment by onlybond** [comment]
Alright. I was actually making the card too. Thanks for the heads up. I will wait for the pr for issue no #06

**Comment by onlybond** [comment]
@Shinjan-saha pr no #20 actually adds the members card with the members page. this issue #7 can become stale. can i work on some other issue.?

**Comment by Shinjan-saha** [comment]
@onlybond sure if you want you can work with other issues but That card is not yet complete and github & linked ID are not there but meanwhile feel free to work in other issues

**Comment by Shinjan-saha** [comment]
@onlybond Card Design part is done you can know update the Data of the card with the members along with  their Github & linkdln profile

**Comment by Shinjan-saha** [comment]
@onlybond work Progress?

**Comment by onlybond** [comment]
@Shinjan-saha is there a list already or do i need to find the profiles and add them?

**Comment by Shinjan-saha** [comment]
@onlybond find the profiles in Github & linkdln and add them

**Comment by onlybond** [comment]
@Shinjan-saha how will i verify if the the members linkedin is the same as the names mentioned. and I am unable find the candidates github too. it will be helpful if a list is provided for the same. so that i can tally the links.

**Comment by Shinjan-saha** [comment]
#26 is looking into it now now response from the assinge for an long time
