### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by Shinjan-saha** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#8]
Basic Structure with Question & answer is given 
Follow the Figma File & create the UI for the FAQ 
use the Q/A already given in basic Structure

**Comment by Sp-Sayan** [comment]
Assign me the issue @Shinjan-saha

**Comment by Shinjan-saha** [comment]
@Sp-Sayan Assigned you the issue best of luck

**Comment by komal-agarwal5** [comment]
#10
