### ISSUE TITLE
Gallery layout

### ISSUE THREAD

**Issue by komal-agarwal5** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#9]
Take reference from the design shown in this Figma file: https://www.figma.com/design/9EePKTLQQBEbIW1FtQKXJJ/Nexus-Website
and work on the gallery page for our website.
(For now you can use dummy images related to the theme)

**Comment by BennyPerumalla** [comment]
Hi @komal-agarwal5 I want to work on the Gallery layout, Please assign this task to me.

**Comment by komal-agarwal5** [comment]
@BennyPerumalla Assigned it to you. Do check the Figma file for reference.Good luck!!

**Comment by BennyPerumalla** [comment]
@komal-agarwal5 Progress till now should i create a new branch and submit the pull request
![Screenshot 2024-10-12 181400](https://github.com/user-attachments/assets/3547cfa5-496c-4332-a561-650924072657)

**Comment by BennyPerumalla** [comment]
Hover part 
![Screenshot 2024-10-12 181647](https://github.com/user-attachments/assets/8a0bc955-a916-40af-979b-ead4d7939315)

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 Progress till now should i create a new branch and submit the pull request ![Screenshot 2024-10-12 181400](https://private-user-images.githubusercontent.com/124452105/375958127-3547cfa5-496c-4332-a561-650924072657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NTc2NjgsIm5iZiI6MTcyODc1NzM2OCwicGF0aCI6Ii8xMjQ0NTIxMDUvMzc1OTU4MTI3LTM1NDdjZmE1LTQ5NmMtNDMzMi1hNTYxLTY1MDkyNDA3MjY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxODIyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2NkMDI1MTkyZjNkNjI4MWYwOTRmNzBkM2JkMDg3MmUyNzZmMzA1NDY4OWFiYjNiNTA4MDk1NDVlOGQ5OWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iP5yQb_AvKlDFCtHSEpMNEoeRSaiq0pU9O5Eko1Fja4)

Arey these boxes normal divs or rectangled images?

**Comment by BennyPerumalla** [comment]
The actual image without zooming out ( Rectagular images/ empty slots for now )
![Screenshot 2024-10-12 235738](https://github.com/user-attachments/assets/d9cb636a-e93a-4f36-904d-7e9f38038036)

**Comment by komal-agarwal5** [comment]
Layout looks good .Can you do one change? That is instead of using blue red images can u use dummy images like some people attending any workshop or related stuff?Much isn't needed just 3-4 images used repeatatively

**Comment by BennyPerumalla** [comment]
![Screenshot 2024-10-13 020758](https://github.com/user-attachments/assets/e2329805-2198-4beb-b62c-2c509557e5e7)
@komal-agarwal5 made as per your instruction

**Comment by Shinjan-saha** [comment]
@BennyPerumalla please don,t create separate branch , Do the PR in main branch only

**Comment by komal-agarwal5** [comment]
@BennyPerumalla Yes looks good and give the PR as Shinjan instructed.
